//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMUPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ID { get; set; }
        public Nullable<double> Electric { get; set; }
        public Nullable<double> Water { get; set; }
        public Nullable<double> Rent_Premises { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<double> SalaryStaff { get; set; }
        public Nullable<double> Goods { get; set; }
        public Nullable<double> Total { get; set; }
    }
}
