//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMUPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Good()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int ID { get; set; }
        public string GoodsCode { get; set; }
        public string GoodsName { get; set; }
        public Nullable<int> ID_Color { get; set; }
        public Nullable<int> ID_Brand { get; set; }
        public Nullable<int> ID_Size { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> ID_Type { get; set; }
        public Nullable<int> Number { get; set; }
        public string Picture { get; set; }
        public Nullable<System.DateTime> Import_Date { get; set; }
        public Nullable<int> ID_Sale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Color Color { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual Size Size { get; set; }
        public virtual Type Type { get; set; }
    }
}
