//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMUPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisionRelationship
    {
        public int ID { get; set; }
        public int ID_User { get; set; }
        public int ID_Permission { get; set; }
        public Nullable<bool> Suspended { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual User User { get; set; }
    }
}
