//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMUPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisionDetail
    {
        public int ID { get; set; }
        public string NameAction { get; set; }
        public string CodeAction { get; set; }
        public Nullable<int> ID_Permision { get; set; }
    
        public virtual Permision Permision { get; set; }
    }
}
